from __future__ import annotations

from pathlib import Path


NIRI_INCLUDE_LINE = 'include "./cfg/bindhub.kdl"'
DEFAULT_NIRI_CONFIG = Path.home() / ".config" / "niri" / "config.kdl"
DEFAULT_NIRI_BINDHUB_FILE = Path.home() / ".config" / "niri" / "cfg" / "bindhub.kdl"

MODIFIER_MAP = {
    "alt": "ALT",
    "ctrl": "CTRL",
    "control": "CTRL",
    "meta": "Mod",
    "super": "Mod",
    "win": "Mod",
    "shift": "Shift",
}

KEY_MAP = {
    "esc": "Escape",
    "escape": "Escape",
    "enter": "Return",
    "return": "Return",
    "tab": "Tab",
    "space": "Space",
    "backspace": "BackSpace",
    "delete": "Delete",
    "insert": "Insert",
    "home": "Home",
    "end": "End",
    "pageup": "Page_Up",
    "pagedown": "Page_Down",
    "left": "Left",
    "right": "Right",
    "up": "Up",
    "down": "Down",
}


def normalize_trigger(trigger: str) -> str:
    parts = [part.strip() for part in trigger.split("+") if part.strip()]
    normalized: list[str] = []

    for part in parts:
        lower = part.lower()
        if lower in MODIFIER_MAP:
            normalized.append(MODIFIER_MAP[lower])
            continue
        if lower in KEY_MAP:
            normalized.append(KEY_MAP[lower])
            continue
        if len(part) == 1 and part.isalpha():
            normalized.append(part.upper())
            continue
        normalized.append(part)

    return "+".join(normalized)


def hotkey_title(hotkey: dict) -> str:
    name = (hotkey.get("name") or "").strip()
    return f"BindHub: {name}" if name else "BindHub"


def render_bind_line(hotkey: dict) -> str:
    trigger = normalize_trigger(hotkey.get("trigger", ""))
    title = hotkey_title(hotkey).replace('"', '\\"')
    hotkey_id = str(hotkey.get("id", "")).replace('"', '\\"')
    return (
        f'    {trigger} hotkey-overlay-title="{title}" '
        '{ spawn "qs" "-c" "noctalia-shell" "ipc" "call" "plugin:bindhub" "runHotkey" "' + hotkey_id + '"; }'
    )


def render_bindhub_file(settings: dict) -> str:
    hotkeys = settings.get("hotkeys", [])
    enabled = []
    seen_triggers: dict[str, str] = {}

    for hotkey in hotkeys:
        if hotkey.get("enabled") is False:
            continue
        trigger = (hotkey.get("trigger") or "").strip()
        if not trigger:
            continue

        normalized = normalize_trigger(trigger)
        if normalized in seen_triggers:
            raise ValueError(
                f"duplicate BindHub trigger detected: {normalized} "
                f"({seen_triggers[normalized]} and {hotkey.get('id', '')})"
            )

        seen_triggers[normalized] = str(hotkey.get("id", ""))
        enabled.append(hotkey)

    lines = [
        "// This file is generated by BindHub.",
        "// Manual changes will be overwritten.",
        "",
        "binds {",
    ]

    if enabled:
        lines.append("    // BindHub global hotkeys")
        for hotkey in enabled:
            lines.append(render_bind_line(hotkey))
    else:
        lines.append("    // No enabled BindHub hotkeys")

    lines.extend(["}", ""])
    return "\n".join(lines)


def ensure_include(config_text: str) -> str:
    if NIRI_INCLUDE_LINE in config_text:
        return config_text

    trimmed = config_text.rstrip()
    if trimmed:
        return trimmed + "\n" + NIRI_INCLUDE_LINE + "\n"
    return NIRI_INCLUDE_LINE + "\n"
